import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "developer Dilruba",
  description: "Generated by dilruba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
<header>header</header>
  
       {children} 
        <footer><h1>This is footer</h1></footer>
       
      </body>
    </html>
  );
}
