import React from 'react'

export default function ProdectDetails({params}) {
    console.log(params.productId)
  return (
    <div>Prodect Details {params.productId}</div>
  )
}


export async function generateMetadata({ params }) {
  return {
    title: `Product ${params.productId}`,
    description: 'Generated by Dilruba',
  };
}